apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.configMap }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
