# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: goochimagne/ibm-interview
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 4
namespace: default
imagePullSecrets: []
nameOverride: ibm-interview
fullnameOverride: ibm-interview-prod

podAnnotations: {}
podSecurityContext: {}

service:
  type: NodePort
  port: 4020

ingress:
  enabled: false

resources: 
  limits:
    cpu: 1.0
    memory: 512Mi
  requests:
    cpu: .01
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

configMap:
  NODE_ENV: production
  TARGET_ENV: production
  PORT: 4020
  HOST: '{{ .Values.fullnameOverride }}'
  MONGODB_CONNECTION_STRING: mongodb://mongodb:27017
  DATABASE_NAME: interview